### ISSUE TITLE
CSV Export not working

### ISSUE THREAD

**Issue by marseeel** [Serial-Studio/Serial-Studio#102]
Hey, I have a problem trying to export the csv. file (on a mac). When having 'create csv file' turned off, the serial output works as expected (a simple plotter), but as soon as I try to do it with it enabled, all I get is this message:

<img width="238" alt="Bildschirmfoto 2022-04-25 um 16 13 44" src="https://user-images.githubusercontent.com/104316237/165112573-f1cdf7c6-8072-427c-b604-bc0b57e389e0.png">

I then have to force quit the application, because the error message just pops up again after pressing 'Ok' or the 'x'. 
Do I do anything wrong, or could this be a problem with macOS?

### The JSON. File
{
    "frameEnd": "",
    "frameStart": "",
    "groups": [
        {
            "datasets": [
                {
                    "alarm": 4000,
                    "fft": false,
                    "fftSamples": 1024,
                    "graph": true,
                    "led": false,
                    "log": false,
                    "max": 5000,
                    "min": 0,
                    "title": "Oszilloskop",
                    "units": "V",
                    "value": "%1",
                    "widget": ""
                }
            ],
            "title": "Graph",
            "widget": ""
        }
    ],
    "separator": "",
    "title": "Oszilloskop"
}

### The arduino File
void setup() {
  Serial.begin(1000000);
}

void loop() {
  int val = analogRead(1);
  Serial.print("/*");
  Serial.print(val);
  Serial.println("*/");
  }

// note: the automatic formating removes the '*' after and before the '/'. (I used the default beginning/end statement)

**Comment by alex-spataru** [comment]
Hi! Did you check the permissions of the folder in which you are storing your CSV files? It is probable that you (or another program) modified the read-write permissions of the `Serial Studio` folder.

You should be able to fix this by inputting the following commands in a Terminal window:

```
cd Documents
find "Serial Studio" -type d -exec chmod 755 {} \;
find "Serial Studio" -type f -exec chmod 644 {} \;
```

If you right-click the `Documents/Serial Studio` folder, the permissions should appear like this:

<img width="377" alt="Screen Shot 2022-05-01 at 3 43 35" src="https://user-images.githubusercontent.com/4225542/166138658-7f1aac0e-0595-4688-9318-6bd8f784d0f5.png">

Please let me know if this fixes your issue!

**Comment by marseeel** [comment]
Yes it did! I had shared my document folder with file sharing, and that caused the problem. Thank you very much, it now works really well!
