### ISSUE TITLE
Use Lua to process received data

### ISSUE THREAD

**Issue by Zhyolo** [Serial-Studio/Serial-Studio#106]
First of all thanks for this great software!

It would be useful to be able to add a script engine such as Lua to  deal with in/out data. By this we can use script to fit different protocols.

**Comment by alex-spataru** [comment]
Hi! Lua was kind of difficult to integrate with Qt, but you can now use JavaScript in the same manner with the [frame parser function](https://github.com/Serial-Studio/Serial-Studio/wiki/Project-Editor#frame-parser-function-view) in the Project Editor :)
