### ISSUE TITLE
Allow for language selection

### ISSUE THREAD

**Issue by not7cd** [Serial-Studio/Serial-Studio#108]
**Is your feature request related to a problem? Please describe.**
Recently working with a friend who had another system language, Serial Studio changed to his locale and become unusable for both of us. We event changed system language in Windows to no effect. 

**Describe the solution you'd like**
Ability to choose program language from the program. Detecting system language is fine, unless it's not mandatory to use it.

**Comment by alex-spataru** [comment]
Hi! You can manually select the desired language by navigating to the settings pane (see image below):

<img width="1166" alt="Screen Shot 2022-05-23 at 14 58 22" src="https://user-images.githubusercontent.com/4225542/169896416-065b7985-093a-4e13-92df-4b3e72d18a49.png">

Please let me know if that fixes your issue!
