### ISSUE TITLE
How to connect to TCP server?

### ISSUE THREAD

**Issue by escherstair** [Serial-Studio/Serial-Studio#110]
I setup a TCP server on localhost, which listens for connections on port 23.
I can test successfully the server with PuTTY, so I'm sure it accepts connections from a TCP client.

I can't find a way to connect from Serial Studio (I tried both the version 1.1.7 and the latest continous build, but none of them works).
The "connect" button that works for a seriel connection is not enabled for TCP, and so I don't know how to connect to the server.
![immagine](https://user-images.githubusercontent.com/22594460/172392346-bf1b4d2e-5113-4434-bb2b-016f0c5eadb4.png)

Can someone help me?

**Comment by mjkl-gh** [comment]
If you type something into the remote adress, such as localhost, it becomes enabled.
![image](https://user-images.githubusercontent.com/9350991/185333673-281ca1c5-4f42-4beb-9ad2-f3d52d0a358a.png)

If you delete the text afterwards. It correctly defaults to the greyed out 127.0.0.1 so it does seem to be a bug of sorts:

![image](https://user-images.githubusercontent.com/9350991/185333782-f9376e52-1fcc-4afd-b67d-411f4ab44abc.png)

I don't know if deleting text, makes it actually default back to 127.0.0.1 or if localhost works. I don't have any active tcp ports on my current device

Remote address does however work with local dns names. So I would assume it works. I can use the network tab to connect to a ser2net server on my network using local dns.
