### ISSUE TITLE
Manually Set Y-Axis Limits on Graphs

### ISSUE THREAD

**Issue by SammiMD** [Serial-Studio/Serial-Studio#120]
Is there a way to manually set the Y-Axis limits on graphs/plots?

I'm measuring pressure, and because my readings all sit around the 1000Pa mark, my plots are coming out as straight lines. I'd like to be able to see the minute fluctuations in the sensors' readings in a plot.

![image](https://user-images.githubusercontent.com/42270353/187581442-6fc2f813-b39d-431c-87fd-6c5a67de920e.png)

TIA

**Comment by alex-spataru** [comment]
Hi, you can modify the Y-axis limits by setting the minimum and maximum values for each dataset in the JSON editor (see screenshot below):

<img width="584" alt="Screen Shot 2022-09-06 at 0 01 43" src="https://user-images.githubusercontent.com/4225542/188550829-d7843452-22f2-4297-82d2-c57943516000.png">

Please let me know if this helped you!

**Comment by phatpaul** [comment]
Any plans to make this adjustable (i.e. with the mouse-wheel) at run-time?

**Comment by alex-spataru** [comment]
> Any plans to make this adjustable (i.e. with the mouse-wheel) at run-time?

Maybe in the future. I think it would be useful to add a window that allows "scaling" signals in a similar way to how you would do it in an oscilloscope.
