### ISSUE TITLE
Dark mode for Windows

### ISSUE THREAD

**Issue by IsaacBlancICL** [Serial-Studio/Serial-Studio#129]
**Is your feature request related to a problem? Please describe.**
The screenshots on the Serial Studio website show the program operating in dark mode (on Mac OS), which I think looks much nicer than the non dark mode Windows version.

**Describe the solution you'd like**
Dark mode for Windows too, please!

**Comment by alex-spataru** [comment]
Hi!

You can change Serial Studio's theme (regardless of the operating system that you are using) by navigating to the "Settings" tab and selecting your desired theme. 

<img width="1166" alt="Screen Shot 2022-10-28 at 1 38 03" src="https://user-images.githubusercontent.com/4225542/198520371-705a5af3-60d2-4739-a281-801bcfd4b7e3.png">

A good idea for the future would be to replicate Window's dark color scheme for a better integration with the rest of the system...

Please let me know if this fixes your issue!

**Comment by IsaacBlancICL** [comment]
Thank you for this. I completely missed that!
