### ISSUE TITLE
Qt version to compile the project

### ISSUE THREAD

**Issue by JesseGuoX** [Serial-Studio/Serial-Studio#130]
## Describe the bug

Hi there.
   Is this project only compiled with Qt6 ? When I compile with Qt5.15 there are a lot of errors about "package import requires a version number", and I think it is a Qt6 feature  which can ignore the module version.

### Screenshots

<img width="286" alt="CleanShot 2022-10-30 at 22 37 31@2x" src="https://user-images.githubusercontent.com/2068290/198884506-1368f4f8-cd12-4771-97ac-b4fc65643b85.png">

**Comment by gremsyQuanLe** [comment]
![image](https://user-images.githubusercontent.com/99642664/198933237-dca0bc0b-45a2-4c55-9c3c-20126c406dd7.png)
I'm Qt 5.15.2 error build

**Comment by alex-spataru** [comment]
Serial Studio is now dependent on Qt 6.8 LTS version, compiling with Qt 5 is not supported (you might be able to work with it, given you change enough things on the QML side). Closing this issue for now.
