### ISSUE TITLE
VT-100 invalid

### ISSUE THREAD

**Issue by heandenX** [Serial-Studio/Serial-Studio#139]
## Describe the bug

In Windows 10 21H2 VT-100 function seems to be invalid

No parsing

~~~
APP_DBG("\033[42;33m abc \033[0m\n");
~~~

### Screenshots

![](https://raw.githubusercontent.com/heandenX/piclib/main/20230228120406.png)

**Comment by heandenX** [comment]
There is no way to pull the scroll bar with autoscroll mode cancelled

**Comment by alex-spataru** [comment]
Fixed in the [latest release](https://github.com/Serial-Studio/Serial-Studio/releases/tag/v3.0.0). Apologies for the delay, and thank you for your patience! It took me a while to figure out how to write a proper VT-100 emulator feature. Closing this issue for now, feel free to re-open it if needed!
