### ISSUE TITLE
LED Status Panel Not Auto-Sizing to Fit All LEDS and Names

### ISSUE THREAD

**Issue by Austin-Oakley-TTI** [Serial-Studio/Serial-Studio#143]
## Describe the bug

The LED Status Panel does not auto size correctly. Some columns of LEDs are not shown in the panel and some names are cut off on the right side. Pulling the panel out to a separate window does not fix the issue. Maximizing sort of fixes it, but with names longer than 6-7 characters, it still does not fit all of them in. 

The ability to split all of my LEDs into several panels would be useful as well, and maybe would be the quicker fix?

Note: I have seen this on v1.1.7 and the latest continuous build https://github.com/Serial-Studio/Serial-Studio/commit/0a16c90acdde2e99a5e78dc158eae38cf0926c19

### Screenshots
I'm using 10 different LEDs. As you can see, the 10th LED name is cut off.
![image](https://user-images.githubusercontent.com/130375679/234409043-c6622645-ed8f-47b9-a637-637372e224fc.png)
![image](https://user-images.githubusercontent.com/130375679/234409179-5bfed5b6-a01c-47a4-946c-b6487d290ebf.png)
![image](https://user-images.githubusercontent.com/130375679/234409264-1519d7fa-99a5-4a28-b215-984f7394c128.png)

## Upload your JSON map file
Here's a snippet from one of the LED datasets.
![image](https://user-images.githubusercontent.com/130375679/234409954-63d9ef56-0872-4952-a29a-5bedafd42f26.png)

**Comment by alex-spataru** [comment]
Fixed in the [latest release](https://github.com/Serial-Studio/Serial-Studio/releases/tag/v3.0.0). Apologies for the delay, and thank you for your patience!
