### ISSUE TITLE
[Feature Request] Allow newlines as frame separators

### ISSUE THREAD

**Issue by kubark42** [Serial-Studio/Serial-Studio#147]
**Describe the feature request**
1. Many native datastreams are sent in a CSV format, with some arbitrary delimiter but always framed by newlines. By allowing CSV formatted streams, these could be ingested directly without requiring the programmer to change the upsource data model. CSV files are extremely common and (presumably) the newline is as robust a data framing as `/*` and `*/` (in the sense that if the newlines are garbled, then the data is corrupted).
1. In a high-speed serial port context, it's nice to minimize how much data is streamed. In my anecdotal case, adding the four bytes of `/*` and `*/` increases my bandwidth needs by 25%.

**Describe the proposed solution**
Allow a newline instead of `/*` and `*/`.

**Comment by alex-spataru** [comment]
Hi! As of the latest release, this feature is available. Just input `\n` or `\r`, or any combination of [these](https://github.com/Serial-Studio/Serial-Studio/blob/master/app/src/IO/Manager.cpp#L42) escape sequences in the [Project Editor](https://github.com/Serial-Studio/Serial-Studio/wiki/Project-Editor) and frame detection will work as expected.

For the moment, you will still need to use a different start & end sequence in Project Mode, if you just want to send CSV-like data, you can do so by using the Quick-Plot mode. In a future I might add the option to not rely on a frame start sequence to parse frames in project mode...maybe we can use a combobox with different "Frame Detection Methods" in the Project Editor for that.
