### ISSUE TITLE
串口选择如果能显示串口的名字信息就好了，只显示COMx选择不太方便

### ISSUE THREAD

**Issue by zengjunfeng** [Serial-Studio/Serial-Studio#155]
![image](https://github.com/Serial-Studio/Serial-Studio/assets/1430435/8d3c782a-8c3f-48e9-8946-caf623cfc4a6)

**Comment by alex-spataru** [comment]
Hi! This feature was implemented by @ZhiyuanYuanNJ in PR #191. Please download the [latest release](https://github.com/Serial-Studio/Serial-Studio/releases/tag/v3.0.0) to give it a try!

---

嗨！此功能已由 @ZhiyuanYuanNJ 在 PR #191 中实现。请下载[最新版本](https://github.com/Serial-Studio/Serial-Studio/releases/tag/v3.0.0)试用一下吧！
