### ISSUE TITLE
UDP send fail with msg "QNativeSocketEngine::write() was not called in QAbstractSocket::ConnectedState"

### ISSUE THREAD

**Issue by goredhawk** [Serial-Studio/Serial-Studio#156]
### Describe the bug

serial studio 2.0.0 use UDP to send data, in console input edit box, type any words, then kit key 'enter', but no data can be sent. 
with a message in the app output **"QNativeSocketEngine::write() was not called in QAbstractSocket::ConnectedState"**
![img_v2_5a1b9c89-c63e-44bf-bf4c-3cece203fb2g](https://github.com/Serial-Studio/Serial-Studio/assets/11162018/0f32c408-d917-4411-b370-ea1f7a3b57a1)

**Here is the UDP settings:**

![img_v2_513bbba0-a0b0-4f0e-9c67-205d59da9f4g](https://github.com/Serial-Studio/Serial-Studio/assets/11162018/392eb177-5e45-4e8e-a53e-8597bd241b4b)

By the way, i clone serial-studio, and compile it with Qt 6.4.3.

**Comment by alex-spataru** [comment]
Hi! I’m closing this issue for now. Please feel free to re-open it if it persists in the latest releases (3.0.x). Based on the error/warning, it seems the UDP socket wasn’t connected, but for some reason, the send control in the console widget was still enabled, which triggered this warning.
