### ISSUE TITLE
Chinese lang filename not match the sources code and some translations wrong

### ISSUE THREAD

**Issue by Himmelt** [Serial-Studio/Serial-Studio#159]
## Describe the bug

Chinese Simplified lang file should be "zh-cn"/"zh_cn"/"zh_CN" but actual is "qt_zh_TW".
And some translations was wrong with 1.1.7. For example, "Quit" should be "退出" but atual is "辞职", "Setup" should be "设置" but actual is "体系". However , I found it's right in sources code at https://github.com/Serial-Studio/Serial-Studio/blob/0a16c90acdde2e99a5e78dc158eae38cf0926c19/assets/translations/zh.ts#L1533-L1536
https://github.com/Serial-Studio/Serial-Studio/blob/0a16c90acdde2e99a5e78dc158eae38cf0926c19/assets/translations/zh.ts#L1831-L1834
So, just needs updating ?

### Screenshots
<img src="https://github.com/Serial-Studio/Serial-Studio/assets/12007165/ad337fa9-b104-40e0-b493-2507dfd13fa6" width=300px/>
<br/>
<br/>
<br/>
<img src="https://github.com/Serial-Studio/Serial-Studio/assets/12007165/d885788c-6d01-4719-9218-349afe186f6d" width=300px/>
<img src="https://github.com/Serial-Studio/Serial-Studio/assets/12007165/c8d4d01c-e7b8-4643-ad48-559159e88300" width=500px/>

**Comment by alex-spataru** [comment]
Hi! Although I don’t speak Chinese, I’ve made an effort to provide helpful translations, as many of our users are Chinese. For the [latest release](https://github.com/Serial-Studio/Serial-Studio/releases/tag/v3.0.0), I used improved translation tools. I’ll close this issue for now, but feel free to re-open it or submit a pull request with any corrections to the translations. Thanks!

--- 

嗨！虽然我不会说中文，但我努力提供了有用的翻译，因为我们有许多中文用户。在最新版本中，我使用了更好的翻译工具。我将暂时关闭此问题，但如果有任何翻译的改进，欢迎重新打开此问题或提交 pull request。谢谢！
