### ISSUE TITLE
Data segmentation

### ISSUE THREAD

**Issue by xiansenzhao** [Serial-Studio/Serial-Studio#162]
There are some ideas in use, would like to consult: Is it possible to divide a row of data according to keywords? This allows for more flexible use in existing projects.
such as:
a123 b123 c123 d123 e123
For example, the above data is divided into multiple groups of data according to abcde.

**Comment by alex-spataru** [comment]
Please take a look at the [frame parser function](https://github.com/Serial-Studio/Serial-Studio/wiki/Project-Editor#frame-parser-function-view) in the Project Editor. You can implement this behavior by writing custom JavaScript code that populates a global array structure based on the keywords that you wish.
