### ISSUE TITLE
support arbitrary baudrate

### ISSUE THREAD

**Issue by LinTeX9527** [Serial-Studio/Serial-Studio#165]
# Feature
Some baudrates are not supported, such as 921600, and it would be nice to be able to edit them manually.

![图片](https://github.com/Serial-Studio/Serial-Studio/assets/10264703/b721638e-a91c-452d-86eb-1684cea18668)

# Version
Continus build, V2.0.0

**Comment by alex-spataru** [comment]
Hi! Sorry for the late reply, I had a very busy year & I'm just beginning to have some free time. You can manually add your own baud rates by just clicking on the baud-rate combo & typing your desired baud rate 😄

If possible, please try this feature & let me know if it works for you too!
