### ISSUE TITLE
功能请求: 请支持 terminal 模式

### ISSUE THREAD

**Issue by heartacker** [Serial-Studio/Serial-Studio#166]
**Is your feature request related to a problem? Please describe.**
当我链接到 linux 等设备的时候， 很希望有 命令行终端模式，类似 linux 的terminal
**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by alex-spataru** [comment]
**普通话（软件翻译，可能包含一些错误......有一天我想学习你的语言）：**

嗨@heartacker！ Serial Studio 对 VT-100 协议有（非常）基本的支持，它允许诸如`clear`之类的命令实际清除终端屏幕。 然而，我还没有真正完成 VT-100 仿真功能的实现。 您可以在“Console -> VT-100 Emulation”菜单项中启用此功能（请查看下面的屏幕截图）。

如果您有兴趣帮助我改进此功能，可以在此处找到 VT-100 仿真代码：[Terminal.cpp](https://github.com/Serial-Studio/Serial-Studio/blob/master/src/UI/Widgets/Terminal.cpp#L601)

**English:**

Hi @heartacker! Serial Studio has (very) rudimentary support for the VT-100 protocol, which allows commands such as `clear` to actually clear the terminal screen. However, I haven't really finished implementing the VT-100 emulation feature. You can enable this feature in the  "Console -> VT-100 Emulation" menu item (check the screenshot below).

If you are interested in helping me out & improve this feature, can find the the VT-100 emulation code here: [Terminal.cpp](https://github.com/Serial-Studio/Serial-Studio/blob/master/src/UI/Widgets/Terminal.cpp#L601)

<img width="852" alt="Screen Shot 2023-10-10 at 12 37 55" src="https://github.com/Serial-Studio/Serial-Studio/assets/4225542/6fc4a72f-3ec4-4859-9198-a676d5dd1cd8">
