### ISSUE TITLE
接收数据中文乱码

### ISSUE THREAD

**Issue by XiaoYou0426** [Serial-Studio/Serial-Studio#174]
## Describe the bug

在Arduino上能正常显示，在Serial Studio中会出现中文版乱码情况

### Screenshots

![企业微信截图_17089959351325](https://github.com/Serial-Studio/Serial-Studio/assets/125875311/3fe305f9-cacc-4113-913c-d1e0eaeefaf6)

**Comment by ZhiyuanYuanNJ** [comment]
我刚也遇到此现象，结果查了下发现是我两端波特率设置不一致导致：）
