### ISSUE TITLE
Not working properly windows 10

### ISSUE THREAD

**Issue by ibrahimqazi** [Serial-Studio/Serial-Studio#175]
## Describe the bug

It only opens one time just after first time installation but after that the window is stuck at the point shown in the image. Secondly, although the version is 1.1.7 but in the opening windows it still shows as 1.1.6.

### Screenshots
![image](https://github.com/Serial-Studio/Serial-Studio/assets/8738199/a3036633-9fbd-456e-8db6-71e95c45392f)
![image](https://github.com/Serial-Studio/Serial-Studio/assets/8738199/28646e6c-f4cc-478a-a62e-d98fef6b6e16)

![image](https://github.com/Serial-Studio/Serial-Studio/assets/8738199/010cdbe5-ec70-48a6-8a75-841703fd6106)

**Comment by alex-spataru** [comment]
Hi! 

I forgot to update the splash screen design/image when I released the 1.1.7 version. Regarding the application freeze, does this issue still occur with the [continuous/beta](https://github.com/Serial-Studio/Serial-Studio/releases/tag/continuous) release?

Thanks,
Alex

**Comment by ibrahimqazi** [comment]
> Hi!
> 
> I forgot to update the splash screen design/image when I released the 1.1.7 version. Regarding the application freeze, does this issue still occur with the [continuous/beta](https://github.com/Serial-Studio/Serial-Studio/releases/tag/continuous) release?
> 
> Thanks, Alex

Perfect, this version does not cause any freezing issue. Thank you
