### ISSUE TITLE
The download link in github didn't work.

### ISSUE THREAD

**Issue by mianqi2016** [Serial-Studio/Serial-Studio#177]
This address - https://github.com/Serial-Studio/Serial-Studio/releases/tag/v1.1.7 didn't work, I downloaded it here - https://sourceforge.net/projects/serial-studio.mirror/, maybe the github page need an update.

**Comment by alex-spataru** [comment]
Hi, I just tested all downloads and they seem to be working for me. Is the issue still present on your side? I haven't updated this project in a while due to work compromises, but I will eventually draft a new release sometime this year.

**Comment by mianqi2016** [comment]
The "connect/disconnect" button a little confusion...
