### ISSUE TITLE
[Feature request] Add connect/disconnect button

### ISSUE THREAD

**Issue by MCUdude** [Serial-Studio/Serial-Studio#18]
Hi!

The user interface is already quite nice, and I like the idea that you automatically connect to the serial port when you select it. However, it would be nice if there was a connect/disconnect button in the toolbar. The reason this would be practical is when you need to re-upload code to your microcontroller. At the moment you'll have to select another serial port and re-select it to reconnect. A simple connect/disconnect button (green/red button perhaps?) would make this process even more elegant.

Another idea: why not have read/write mode selected by default? In most cases it's not harmful to write to the connected device.

**Comment by alex-spataru** [comment]
Hi, I am currently using this approach for other (proprietary) projects. Here are some screenshots of the button, which is located at the toolbar: 

![Screen Shot 2021-02-01 at 13 53 32](https://user-images.githubusercontent.com/4225542/106504573-20e95780-6495-11eb-885f-148e739c91ad.png)

![Screen Shot 2021-02-01 at 13 53 38](https://user-images.githubusercontent.com/4225542/106504581-234bb180-6495-11eb-96ad-b6bad13fe105.png)

Please let me know if you like that design, or if have another idea. I'll change the default open mode to RW to avoid confusion among new users of the project.

**Comment by MCUdude** [comment]
That looks very good!

> I'll change the default open mode to RW to avoid confusion among new users of the project.

Excellent! I'm sure this would suit most users.

**Comment by alex-spataru** [comment]
I did some UI revamps and added the conenct/disconnect button. Here are the screenshots:

![Screen Shot 2021-02-01 at 19 11 16](https://user-images.githubusercontent.com/4225542/106534285-c4506180-64c1-11eb-9439-25aff7247842.png)

![Screen Shot 2021-02-01 at 19 10 58](https://user-images.githubusercontent.com/4225542/106534290-c61a2500-64c1-11eb-94d2-92ab18ed6c58.png)

Having this button is indeed more intuitive than changing the serial devices combobox. And it can be accessed even if the setup pane is hidden.

**Comment by alex-spataru** [comment]
Hi, this feature is now available with the [latest release](https://github.com/Serial-Studio/Serial-Studio/releases/tag/v1.0.13). Please let me know if we should close this issue.

**Comment by MCUdude** [comment]
This turned out REALLY GOOD! Issue can definitly be closed.
