### ISSUE TITLE
希望能够添加一个普通上位机的功能,就像Vofa+一样，可以发送普通的字符或者十六进制数，或者能够按照特定字符格式提取数据并显示到图形化界面

### ISSUE THREAD

**Issue by 12mbw** [Serial-Studio/Serial-Studio#182]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by alex-spataru** [comment]
Thank you for your suggestion! I understand that VOFA+ is a popular tool, especially among Chinese users, and I appreciate you comparing it to my software.

I’d like to clarify that my software already supports sending data in hexadecimal format and reading binary data. It also provides advanced features like custom JavaScript frame parsing, high-frequency data handling, and robust visualization options, which make it highly flexible for a variety of use cases.

While my documentation is in English and I don’t speak Chinese, I’m always open to feedback and suggestions from all users. If there are specific features or improvements you’d like to see, please don’t hesitate to share more details—I’d be happy to explore them!

I will now close this issue. If you have a specific request, please feel free to open a new issue with more details.

---

谢谢您的建议！我知道 VOFA+ 是一个很受欢迎的工具，尤其是在中国用户中，我很感谢您将其与我的软件进行比较。

我想澄清一下，我的软件已经支持发送十六进制格式的数据并读取二进制数据。此外，它还提供了许多高级功能，例如自定义 JavaScript 帧解析、高频数据处理以及强大的可视化选项，使其在各种使用场景中都非常灵活。

尽管我的文档是英文的，而且我不会说中文，但我始终愿意倾听来自所有用户的反馈和建议。如果您有任何具体的功能或改进需求，请随时告诉我，我很乐意进行探索！

我将关闭此问题。如果您有具体的功能请求，请随时打开一个新的问题并提供更多详细信息。
