### ISSUE TITLE
Crash of the program when opening the widget window

### ISSUE THREAD

**Issue by PlanNi4** [Serial-Studio/Serial-Studio#192]
## Describe the bug

Hi, I am using qt 6.7.1 and compiling the project using MSVC2019 64 bit and using Serial studio 2.0.0. The project is compiled, however, when the data is trying to be visualized using widgets, the following error occurs (attached screenshot). Going through the various options, I found out that this happens when Gauge is selected in the widget settings. Help me, please

### Screenshots

![image](https://github.com/Serial-Studio/Serial-Studio/assets/171622164/7e42ba0a-a29e-4607-a6f2-e3337e83a463)

## Upload your JSON map file*

[HJ.json](https://github.com/user-attachments/files/15539622/HJ.json)

## Upload minimal Arduino program to replicate your issue

```

If you need me to test with a specific microcontroller, please consider [donating](https://www.paypal.com/donate?hosted_button_id=XN68J47QJKYDE) so that I can buy that MCU and help you!

**Comment by alex-spataru** [comment]
Hi! This issue stemmed from how Serial Studio handled Qwt widget rendering on the dashboard, which led to significant performance issues, particularly on older hardware. Please try the [latest release](https://github.com/Serial-Studio/Serial-Studio/releases/tag/v3.0.0) and let me know if the issue persists. In this version, I’ve made substantial improvements to the rendering process—including GPU utilization for widget and terminal rendering—to significantly reduce CPU load, prevent event thread overload, and enhance overall stability.

I’ll close this issue for now, but please feel free to re-open it if you still encounter the crash or any related issues in the latest version. Thanks, and I hope this release resolves it for you!
