### ISSUE TITLE
通过base64、010二进制加密等方法，对两端制定文件夹的文件进行双端自动同步。

### ISSUE THREAD

**Issue by ruchid123123** [Serial-Studio/Serial-Studio#201]
通过base64、010二进制加密等方法，对两端制定文件夹的文件进行双端自动同步。

**Comment by alex-spataru** [comment]
> 通过base64、010二进制加密等方法，对两端制定文件夹的文件进行双端自动同步。
> **(Translation)** Automatically synchronize files in designated folders on both ends through base64, 010 binary encryption and other methods.

Hi. I don't understand what you are trying to do, which files, which folders? Are you referring to the serial port (or network) communications between the application and the connected device? To the CSV files? Please explain and be more specific 😄 

**（翻译）** 你好。我不明白你想做什么，哪些文件，哪些文件夹？你指的是应用程序和连接设备之间的串行端口（或网络）通信吗？指的是 CSV 文件吗？请解释一下，更具体一点 😄
