### ISSUE TITLE
关于窗口问题

### ISSUE THREAD

**Issue by QQ-X5zj** [Serial-Studio/Serial-Studio#204]
## Describe the bug

关于窗口问题

### Screenshots

![image](https://github.com/user-attachments/assets/ce2644b2-2b36-49da-a1f8-cb70253eb0c0)

## Upload your JSON map file*

This is important in order to reproduce any UI-related issues.

## Upload minimal Arduino program to replicate your issue

This is important so that I can replicate the environment and setup that causes the bug. 

An example program could be:

```cpp
void setup() {
    Serial.begin(115200);
    while (!Serial);
}

void loop() {
    Serial.println("/*1,2,3*/");
    delay(50);
}
```

If you need me to test with a specific microcontroller, please consider [donating](https://www.paypal.com/donate?hosted_button_id=XN68J47QJKYDE) so that I can buy that MCU and help you!

**Comment by alex-spataru** [comment]
Hi! Could you check if this issue still occurs with the latest continuous build? You can download it [here](https://github.com/Serial-Studio/Serial-Studio/releases/tag/continuous).

Let me know if this resolves the problem!

---

你好！你能否检查一下在最新的持续构建版本中这个问题是否仍然存在？你可以在[这里](https://github.com/Serial-Studio/Serial-Studio/releases/tag/continuous)下载。

请告诉我是否解决了问题！
