### ISSUE TITLE
QT .dll crashing after first time opening

### ISSUE THREAD

**Issue by gblough** [Serial-Studio/Serial-Studio#206]
I am in IT and we are trying to troubleshoot an issue with a particular user.

When he installs and runs the program for the first time, it runs without issue.  After that, the program crashes due to some the the QT .dll files crashing.  Here are the reports form event viewer:

Faulting application name: SerialStudio.exe, version: 0.0.0.0, time stamp: 0x65fbe0fc
Faulting module name: Qt6Gui.dll, version: 6.5.3.0, time stamp: 0x650d339f
Exception code: 0xc000041d
Fault offset: 0x00000000000e3810
Faulting process id: 0x0x262C
Faulting application start time: 0x0x1DB0E7DBF0F3AA2
Faulting application path: C:\Users\REDACTED\Desktop\MRD_PROVISION\SerialStudio-2.0.0-Windows\SerialStudio.exe
Faulting module path: C:\Users\REDACTED\Desktop\MRD_PROVISION\SerialStudio-2.0.0-Windows\Qt6Gui.dll
Report Id: 50fee831-263a-4396-9a2b-74be1f7abb9a
Faulting package full name:
Faulting package-relative application ID: 

We have no other users having this issue.  We have tried reinstalling and it's still causing some problems.  

I am no programmer so I am not sure what to do from here.

Thanks for your help!

**Comment by gblough** [comment]
If you need any other information, just let me know.  Happy to get that to you!

**Comment by alex-spataru** [comment]
Hi! Does this issue still occur with the [latest release](https://github.com/Serial-Studio/Serial-Studio/releases/tag/v3.0.0)? I’ve made several updates and upgraded to Qt 6.8 LTS, which may help resolve this. In previous versions, Serial Studio had a lot of problems on older systems, as the widgets and the terminal were rendered using a QPainter, which consumed significant CPU time and interfered with the event system.

The latest version is designed to be much more efficient, using GPU rendering whenever possible and only re-painting widgets/terminal when necessary. It’s also more stable—I’ve tested it on 10+ year-old laptops running Linux and Windows 10 with no freezes or hang-ups, even in highly demanding dashboard setups. I hope this release resolves your issue, please let me know how it works for you (and your user).

**Comment by alex-spataru** [comment]
Closing this issue, feel free to re-open if needed.
