### ISSUE TITLE
Issues related to the data monitoring function

### ISSUE THREAD

**Issue by Bob-sketch234** [Serial-Studio/Serial-Studio#211]
After connecting to the serial port using your software, my other software can not connect to the serial port

**Comment by alex-spataru** [comment]
Hello! This behavior is standard across all operating systems: serial ports cannot be accessed by multiple applications simultaneously. When a serial port is in use by one application, it remains locked to other applications until released.

To use the serial port device in another application, please either click the “Disconnect” button in Serial Studio or close Serial Studio entirely. This will free up the port for your other software to connect.
