### ISSUE TITLE
Multi plot no legend

### ISSUE THREAD

**Issue by yannislagnel** [Serial-Studio/Serial-Studio#221]
## Describe the bug

Hello,
Tested on macOS 15 and windows 10
With version 2.0 or less when using "multiple plot" we have the legend for each data serie 
But  with versions >=3.0 I didn't find any legend and it is not possible to identify each data serie 

### Screenshots
Version 2.0
![Screenshot 2024-11-15 at 17 44 34](https://github.com/user-attachments/assets/d165403b-ade4-4617-b049-01cd9bd2a5dc)
version 3.04
![Screenshot 2024-11-15 at 17 40 40](https://github.com/user-attachments/assets/8b8e1a0b-9ece-47c0-8e8c-043fed4ccd9f)

## Upload your JSON map file*

This is important in order to reproduce any UI-related issues.

[Untitled Project.json](https://github.com/user-attachments/files/17778564/Untitled.Project.json)

## Upload minimal Arduino program to replicate your issue

This is important so that I can replicate the environment and setup that causes the bug. 

An example program could be:
   Serial.print(">");
    Serial.print(tot_angle);
    Serial.print(",");
    Serial.print(u);
    Serial.print(",");
    Serial.print(error);
    Serial.print(",");
    Serial.print(pwmL);
    Serial.print(",");
    Serial.print(pwmR);
    Serial.print(",");
    Serial.print(desired_angle);
    Serial.print(",");
    Serial.print(kp);

    Serial.print("\n");
If you need me to test with a specific microcontroller, please consider [donating](https://www.paypal.com/donate?hosted_button_id=XN68J47QJKYDE) so that I can buy that MCU and help you!

**Comment by alex-spataru** [comment]
Hi! Just fixed this issue, you can try it out in the latest [continuous build](https://github.com/Serial-Studio/Serial-Studio/releases/continuous). You can also now enable/disable showing legends on multiple plot widgets using the "Show Legends" checkbox in the widget setup panel:

<img width="1163" alt="Screenshot 2024-11-16 at 3 17 40 p m" src="https://github.com/user-attachments/assets/596d5095-9256-4f29-8476-47cda811350b">

**Comment by yannislag** [comment]
Hi Alex, 
Thank you for your reactivity.
I installed this version and It works very well.
Thank you again. 
Yannis

**Comment by alex-spataru** [comment]
You're welcome! Closing this issue to keep things clean...
