### ISSUE TITLE
Dragging the playback cursor shows wrong data on graphs

### ISSUE THREAD

**Issue by nono313** [Serial-Studio/Serial-Studio#43]
**Describe the bug**
When opening a CSV and using playback feature, graph data get wrong.
If we move manually the playback cursor (dragging the cursor from left to right and to left again), the graph line get rewritten.
It seems that the data value corresponding to the playback position is appended to the end of the graph line.
This means that for a value that goes continuously from 0 to 90, if we move to different points using the playback cursor (dragging the cursor), the line no longer shows a continuous line from 0 to 90 but shows 'waves' instead. The graph line then no longer reprenst the history of the data before the current point.

**To Reproduce**
1. Record some data with graph enabled
2. Open the CSV of the data
3. Manually drag the playback cursor to different position and obverse the line graph.

**Expected behavior**
Two possibilities here : 
a. Display the whole data in the graph and use a visual cursor showing the current time from the playback cusor
b. Erasing data when dragging the cursor backward and rewrite the whole data when moving forward (up to the selected point).

Personally I think solution a would be better and maybe easier to implement.

**Screenshots**
Example below show normal playback (played from start to end) : look at the Distance graph.
![2021-03-03 08_50_01-Serial Studio v1 0 18](https://user-images.githubusercontent.com/2676389/109771850-9a43a980-7bfd-11eb-98d5-a2c93a9dbae1.png)
Example below show the same data, but after I dragged the mouse on the cursor from 0 to 20% back and forth several times. We see that the data is rewritten and shows 'waves'.
![2021-03-03 08_50_24-Serial Studio v1 0 18](https://user-images.githubusercontent.com/2676389/109771867-9e6fc700-7bfd-11eb-81b2-1cad7c13d239.png)

**Upload your log file**

[17-21-52.csv.txt](https://github.com/Serial-Studio/Serial-Studio/files/6074375/17-21-52.csv.txt)

**Upload your JSON map file**

[serialstudio.json.txt](https://github.com/Serial-Studio/Serial-Studio/files/6074380/serialstudio.json.txt)

**Comment by alex-spataru** [comment]
Fixed on version `3.0.4` onwards, sorry for the delay 😄
