### ISSUE TITLE
Are /* */ frames required in MQTT?

### ISSUE THREAD

**Issue by 2e0byo** [Serial-Studio/Serial-Studio#51]
...short answer to which is 'no, at least not with this build this end'.

I'm assuming that the `/*` and `*/` are serial only? (which makes sense).  In this case I'll open a PR for the wiki.

Is this also the case with the udp/tcp connection? (I plan to do some work with it shortly, so I can figure it out if nobody knows).

I've just modified [OpenFridge](https://gitlab.com/2e0byo/OpenFridge/-/tree/serial-studio) to spew out data in a format readable by Serial Studio, and now I have a nice pretty dashboard for free!  I bet you didn't expect it would be used to watch the temperature of a fridge :D

Thanks for a very exciting project!

**Comment by alex-spataru** [comment]
Hi! 

For MQTT the start/end frame sequences are not required. These are only used for separating frames in the I/O module, which currently supports:

- Serial port
- TCP/UDP socket

You can find the code for the IO module in [this directory](https://github.com/Serial-Studio/Serial-Studio/tree/master/src/IO). The function that separates incoming data frames is implemented [here](https://github.com/Serial-Studio/Serial-Studio/blob/master/src/IO/Manager.cpp#L488).

To be honest, I never expected this project to be used to graph data generated by a fridge 😆 

Thanks for your interest in this project!
