### ISSUE TITLE
Dashboard&Widgets is not working，how to fix？

### ISSUE THREAD

**Issue by he2002512** [Serial-Studio/Serial-Studio#52]
![image](https://user-images.githubusercontent.com/33870986/115731274-96403680-a3b9-11eb-8774-97ea1f2378f5.png)
How to use the Dashboard&Widgets?

**Comment by Ewpratten** [comment]
I am also trying to figure this one out too

**Comment by Ewpratten** [comment]
And a few minutes later, I found my issue. I wasn't using the `/*` and `*/` around my data.

**Comment by alex-spataru** [comment]
Last but not least, [here](https://github.com/Serial-Studio/Serial-Studio/wiki/Communication-Protocol) is an article that details the structure of the JSON file, please let me know if it helps you!

**Comment by he2002512** [comment]
@alex-spataru  Yes ，it works!  I wasn't using the /* and */ ,too.  Thank you alex-spataru ,Thank you Ewpratten !
