### ISSUE TITLE
logarithmic scales :) ?

### ISSUE THREAD

**Issue by 3mrrrx** [Serial-Studio/Serial-Studio#55]
logarithmic scales for plots would be good to have for some kinds of data/signals

**Comment by alex-spataru** [comment]
Hi, I just integrated Serial Studio with [qwt](https://qwt.sourceforge.io/index.html) in the last commits. I am currently working on "porting" the previous QML/JS widgets to Qwt. Once I finish that (and familiarize myself with Qwt), I'll begin implanting more advanced graphs, including logarithmic scales and FFT/DFT plots (#49).

**Comment by alex-spataru** [comment]
Hi, I just implemented this feature. Here is an example of the generated plot (with a rather unassertive dataset - altitude in meters):

![Screen Shot 2021-10-07 at 18 56 53](https://user-images.githubusercontent.com/4225542/136477595-73a6550f-a59b-4a27-92dc-cf911ddf7ca5.png)

To enable a logarithmic plot, you need to enable both the "generate plot" and "logarithmic plot" options in the JSON Editor window:

![Screen Shot 2021-10-07 at 19 02 45](https://user-images.githubusercontent.com/4225542/136477986-6d1e48c1-b605-4f8a-9830-a29538fe1ba6.png)

Please let me know what you think about this! I'll mention in this thread when a draft a new release containing this feature.

**Comment by alex-spataru** [comment]
I just created a [new release](https://github.com/Serial-Studio/Serial-Studio/releases/tag/v1.1.0) that implements this feature. Please let me know how it works for you!

**Comment by alex-spataru** [comment]
I will close this issue due to lack of responses and to keep things clean. If you encounter problems please feel free to open this issue again :)
