### ISSUE TITLE
“port” in the setting pad should be translated into “端口”, not “港口”

### ISSUE THREAD

**Issue by MiKiJT** [Serial-Studio/Serial-Studio#57]
![image](https://user-images.githubusercontent.com/35521558/117773532-016b8300-b26b-11eb-9599-584b781ee74e.png)

**Comment by alex-spataru** [comment]
Thanks a lot for the report! I just updated the translations to fix this issue with the [latest](https://github.com/Serial-Studio/Serial-Studio/commit/e59773b8a208d4aad83a6b5166296f08ca92bc1f) commit. See screenshot below:

<img width="310" alt="Screen Shot 2021-05-12 at 12 51 37 AM" src="https://user-images.githubusercontent.com/4225542/117925200-816e0900-b2bc-11eb-95f0-90ba2f36afa7.png">

**Comment by Frenkenstein6** [comment]
Thank you.

**Comment by alex-spataru** [comment]
The issue should be fixed with the latest release. Feel free to re-open this issue if I forgot something :shipit:
