### ISSUE TITLE
Network.cpp constructor function  negligent mistake

### ISSUE THREAD

**Issue by senliontec** [Serial-Studio/Serial-Studio#59]
In Network.cpp 

The Constructor function,

line 43, "connect(&m_udpSocket, &QTcpSocket::errorOccurred, this, &Network::onErrorOccurred);"

I think it should be: connect(&m_udpSocket, &QUdpSocket::errorOccurred, this,&Network::onErrorOccurred);

I am not sure, please check it

**Comment by alex-spataru** [comment]
Thanks a lot for the code review! Fixed.
