### ISSUE TITLE
gauge widget

### ISSUE THREAD

**Issue by Bischtinius** [Serial-Studio/Serial-Studio#64]
First of all, thank you for this software. It helps a lot with my studies.

We made an RC-Car in university and I thought it would be nice to show the vehicle speed on a gauge.

I think a widget which is a gauge could be a nice feature 
Like in the “bar” widget the JSON could include “min” and “max” and the value

**Comment by alex-spataru** [comment]
Hi, as of the latest commit you can now use gauge widgets within Serial Studio:

<img width="752" alt="Screen Shot 2021-09-03 at 13 50 52" src="https://user-images.githubusercontent.com/4225542/132053417-f08e8ec6-8dc8-4e3d-8cbb-95530d10a9f2.png">

Here is the JSON code for widget usage:

```
{
   "t":"Title", 
   "v":"%value%,  
   "w":"gauge",  
   "min":%min_value%, 
   "max":%max_value%
}
```

I will notify you when I draft a new release containing this change. Please let me know what you think about it!

**Comment by alex-spataru** [comment]
*Update:* I just created a new [release](https://github.com/Serial-Studio/Serial-Studio/releases/tag/v1.0.21) that implements this widget. Documentation for the gauge widget is available [here](https://github.com/Serial-Studio/Serial-Studio/wiki/Introduction-to-widgets#gauge). Please let me know if I should close this issue.

**Comment by Bischtinius** [comment]
I tested the gauge widget today and if I configure it in the JSON the "Widget" option in the UI is not active.
I manged to work around the problem with a bar widget and then change the JSON.
I can say that the Widget itself works perfectly but the UI button "Widget" stays inactive.
![grafik](https://user-images.githubusercontent.com/20275800/133634396-f2c2db68-4fd8-4114-9003-e8c4e93d9b77.png)

**Comment by alex-spataru** [comment]
Hi @Bischtinius, I fixed that issue in commit 050f64e749db10c1e29a159c8283560d78387026. I will notify you when I draft a new release containing this fix.

Thanks for the report!

**Comment by alex-spataru** [comment]
The issue should be fixed with the [latest](https://github.com/Serial-Studio/Serial-Studio/releases/tag/v1.0.22) release. Please let me know if it works for you!

**Comment by Frenkenstein6** [comment]
Looks Great
