### ISSUE TITLE
Maybe tag a new release?

### ISSUE THREAD

**Issue by umarcor** [Serial-Studio/Serial-Studio#68]
The last release was tagged back in march: https://github.com/Serial-Studio/Serial-Studio/tree/v1.0.20.
@alex-spataru, how do you feel about tagging a new one so that I can update the package in MSYS2?

**Comment by alex-spataru** [comment]
Hi, I'll draft a new release as soon as I can confirm that issue #66 is fixed without any regressions & finish implementing the gauge widget (#64). I'll keep you updated with my progress (even if its slow right now), thanks for the support!

**Comment by umarcor** [comment]
No rush at all! Just ping me whenever you feel like bumping!

**Comment by alex-spataru** [comment]
Hi @umarcor! I just created a new release. Thanks a lot for the help!
