### ISSUE TITLE
CSV export doesn't strip frame end characters

### ISSUE THREAD

**Issue by dwhitters** [Serial-Studio/Serial-Studio#71]
**Describe the bug**
For a frame: /*Frame,1,2,3*/, in the CSV, the '3' will be recorded as "3*/".

**To Reproduce**
1. Allow CSV Exporting
2. Open the CSV

**Environment**
Ubuntu 21.04

**Expected behavior**
The frame end characters will not be present in the CSV.

**Screenshots**
![image](https://user-images.githubusercontent.com/7851196/134339923-247b6ba5-9d92-4a9a-aa3c-8272408c9190.png)

**Comment by alex-spataru** [comment]
Hi, I just fixed this issue. I'll draft a new release in a moment.

**Comment by alex-spataru** [comment]
I just created a [new release](https://github.com/Serial-Studio/Serial-Studio/releases/tag/v1.0.23) that fixes this issue. Please let me know if it works for you too!

**Comment by dwhitters** [comment]
The issue has been resolved, thanks for the quick turnaround!
