### ISSUE TITLE
Virtual Com Port Support

### ISSUE THREAD

**Issue by mcgdb** [Serial-Studio/Serial-Studio#73]
**Describe the bug**
I don't have any hardware on hand, but I wanted to test out this cool test suite.  I thought of creating a virtual com port with socat and just piping data into it with python or something, but I can't select the virtual com port in Serial-Studio.

**To Reproduce**
1. create a virtual com port with `socat -x -v PTY,link=$HOME/dev/modem0 PTY,link=$HOME/dev/modem1`
4. Serial-Studio will not recognize either of these as valid serial ports

**Expected behavior**
To allow connecting to the virtual serial port in the COM port drop down 

**Screenshots**
N/a

**Upload your log file**
N/a

**Upload your JSON map file**
N/a

**Comment by alex-spataru** [comment]
Hi, I will check this issue during the course of the weekend. Are you using Linux? I have never tried creating virtual com ports before.

**Comment by JLuij** [comment]
Hey @alex-spataru, was this implemented in the end? We'd like to forward serial output of a peripheral connected to a Linux PC (already on a serial port) to serial studio :)

**Comment by tarman3** [comment]
Want to plot data of signal from LTE modem.
I also try to use virtual com port without result.
I found solution with using **MQTT**.

In Archlinux install MQTT Broker - [mosquitto](https://mosquitto.org/)
`sudo pacman -S mosquitto`

In terminal run **mosquitto** with default settings
`mosquitto --verbose`

Run **Serial-Studio** and connect to MQTT broker.
host: 127.0.0.1
topic: lte
mode: Subscriber
Keep Alive: 3600
other settings stay default

![Screenshot_20241114_170517](https://github.com/user-attachments/assets/d9b13503-826d-47fb-afd7-3e1a633028bc)

It is possible to send data from terminal.
`mosquitto_pub -m "100,50,75,89" -t "lte"`

I using python to parse data from LTE modem API.
Create file lte_mqtt.py
```
#!/usr/bin/env python

import requests
import time
import datetime
import xml.etree.ElementTree as ET
import re
import paho.mqtt.client as paho

url_api = 'http://192.168.9.1/api/device/signal'
cycle_time = 5
mqtt_topic = 'lte'
mqtt_broker_ip = '127.0.0.1'
mqtt_broker_port = 1883

def get_value(marker):
    string = tree.find(marker).text
    value = re.search(r'(\-|)(\d+)(\.?)(\d*)', string).group(0)
    # print('string=', string, ' value=', value)
    return value

mqttc = paho.Client()
mqttc.connect(mqtt_broker_ip, mqtt_broker_port, 60)

while True:
    xml_data = requests.get(url_api).text
    tree = ET.XML(xml_data)

    cell = str(get_value('cell_id'))
    rsrq = int(float(get_value('rsrq')))
    rsrp = int(get_value('rsrp'))
    rssi = int(get_value('rssi'))
    sinr = int(get_value('sinr'))

    pci = int(get_value('pci'))
    mode = int(get_value('mode'))
    ulbandwidth = int(get_value('ulbandwidth'))
    dlbandwidth = int(get_value('dlbandwidth'))
    band = int(get_value('band'))
    ulfrequency = int(get_value('ulfrequency'))
    dlfrequency = int(get_value('dlfrequency'))

    print(f'{datetime.datetime.now().strftime("%H-%M-%S")} CELL={cell} RSRQ={rsrq} RSRP={rsrp} RSSI={rssi} SINR={sinr}')
    frame = f'{rsrq},{rsrp},{rssi},{sinr}'
    # print(frame)
    mqttc.publish(mqtt_topic, frame)

    time.sleep(cycle_time)
```

Before run need to install Python client library for MQTT - **paho**
`sudo pacman -S python-paho-mqtt`
`python lte_mqtt.py`

After get first frame of data Serial-Studio will automatic open dashboard with plots.

![Screenshot_20241114_173624](https://github.com/user-attachments/assets/37b5f34f-da8c-4405-ae1e-ce3f468b007c)

Hope this information will be useful for someone else.

**Comment by alex-spataru** [comment]
@tarman3 Nice solution! I need to dedicate some time to add support for virtual serial ports on Linux. You are welcome to add this solution to the [wiki](https://github.com/Serial-Studio/Serial-Studio/wiki) for new users (so that they don't need to search on GitHub issues until they find a solution). Another alternative approach can be to create a Python script that publishes data on a TCP or UDP socket, and use the "Network Socket" driver to directly access the data. You can find a C-based example of this in the [UDP Function Generator Example](https://github.com/Serial-Studio/Serial-Studio/tree/master/examples/UDP%20Function%20Generator).

**Comment by tarman3** [comment]
> You are welcome to add this solution to the [wiki](https://github.com/Serial-Studio/Serial-Studio/wiki)

Maybe will be to add this solution to [examples](https://github.com/Serial-Studio/Serial-Studio/tree/master/examples)?
I can try to create pull request.

**Comment by alex-spataru** [comment]
> Maybe will be better add this solution to [examples](https://github.com/Serial-Studio/Serial-Studio/tree/master/examples)?

In hindsight, yes, that would be a great idea. I’m not sure if users outside the Serial Studio organization have permissions to edit the wiki...Thank you!

**Comment by tarman3** [comment]
Issue solved
