### ISSUE TITLE
With the last 1.1.0 version the Socket udp don't work

### ISSUE THREAD

**Issue by bigjohnson** [Serial-Studio/Serial-Studio#76]
I have an udp esp8266 sending script that I used happily with previous version, but with the last version if I try to connect with the esp 8266 at the adress 192.168.0.122 appear this error
![immagine](https://user-images.githubusercontent.com/2248402/138072559-bdcb7546-44f7-42d8-8580-38313ca93b5a.png)
translating from italian:

the address is unavailable

I think that you broke UDP protocol mixing local / remote address with the new Multicast feature.

When you connect in UDP **without multicast** you must connect to remore address.

When you connect in UDP **with multicast** you must start receiving data on a multicast address binded on the local machine.

Thanks for the new relase wit allot of new fwatures.

**Comment by alex-spataru** [comment]
Thanks a lot! Please let me know if the UDP multicast connection also works for you. If so, I shall create a new release as soon as possible.
