### ISSUE TITLE
More flexible data format

### ISSUE THREAD

**Issue by n-e-g** [Serial-Studio/Serial-Studio#93]
It would be super useful to be able to process data frames containing different data.
I found this issue when trying to use serial studio in my projects that send different data in different frequencies.
E.g. packet data is tagged like `SPD=10,ACCX=3,ACCY=4,ACCZ=0` that is sent very frequently, while e.g. power status like `PWR=30` is send occasionally. In general Some packets contain data that change frequently, some infrequently. 
As currently it is required to send all data within single frame, it is kind of impractical and not that flexible.
I would like to extract particular fields and values, map them to datasets and update only these datasets.

Additionally, this would allow serial studio to be used to extract data from existing protocols without changing of message format.

I can imagine implementing this as being able to add variables like `%{SPD}` instead of `%1`, use values as replecements and remove groups that contain unfilled/missing data. Then append just that datasets.

Another possibility is to have intermediate plugin (e.g. with json file) that is able to map between tag names and indices, leaving unmatched %X field as zeros, or filter them out (probably better).

**Comment by n-e-g** [comment]
After thinking about this problem, I think that the most flexible implementation would be to have intermediate component that receives frame, analyzes its content, and produces data structure that is later on filled into the data sets.
This would allow even further utilization of existing protocols as data sources. E.g. by different header byte the data format could be different, even without tagged data, like `SPD,10`, `ACC,1,2,3` and so on ...
I can imagine implementation that splits definition of data sets, layouts, etc and data format definition (2 jsons) configured independently.

Btw, I kave no qt knowledge, but I am software engineer, so I could help implementing this feature if you find it useful.

**Comment by alex-spataru** [comment]
I was thinking about modifying the JSON project format to something similar to this (example):

```json
{
  "mqtt": {
    "publish": true,
    "brokerAddress": "mqtt://broker.example.com",
    "port": 1883,
    "username": "mqtt_user",
    "password": "mqtt_password",
    "publishTopic": "sensors/data",
    "subscribeTopic": "sensors/commands"
  },
  "frameTypes": [
    {
      "id": "A",
      "type": "hex",
      "startDelimiter": "0xAA",
      "endDelimiter": "0xFF",
      "readings": [
        {
          "name": "temperature",
          "dataType": "float",
          "startIndex": 1,
          "length": 4
        },
        {
          "name": "humidity",
          "dataType": "float",
          "startIndex": 5,
          "length": 4
        },
        {
          "name": "light",
          "dataType": "int",
          "startIndex": 9,
          "length": 2
        },
        {
          "name": "status",
          "dataType": "bit",
          "startIndex": 11,
          "bitIndex": 0
        },
        {
          "name": "battery",
          "dataType": "byte",
          "startIndex": 12
        }
      ]
    },
    {
      "id": "B",
      "type": "csv",
      "startDelimiter": "<",
      "endDelimiter": ">",
      "delimiter": ",",
      "readings": [
        {
          "name": "pressure",
          "dataType": "float",
          "column": 0
        },
        {
          "name": "altitude",
          "dataType": "float",
          "column": 1
        }
      ]
    },
    {
      "id": "C",
      "type": "key-value",
      "separator": "=",
      "startDelimiter": "{",
      "endDelimiter": "}",
      "pairDelimiter": ";",
      "readings": [
        {
          "name": "latitude",
          "key": "lat",
          "dataType": "float"
        },
        {
          "name": "longitude",
          "key": "lon",
          "dataType": "float"
        }
      ]
    }
  ],
  "widgets": [
    {
      "type": "single-signal-plot",
      "category": "Temperature",
      "name": "Temperature Plot",
      "dataSource": "temperature",
      "configuration": {
        "xAxis": "time",
        "yAxis": "temperature",
        "color": "red",
        "minY": -50,
        "maxY": 100,
        "scale": "linear"
      }
    },
    {
      "type": "multiple-signal-plot",
      "category": "Environment",
      "name": "Temperature and Humidity Plot",
      "dataSources": ["temperature", "humidity"],
      "configuration": {
        "xAxis": "time",
        "yAxis": ["temperature", "humidity"],
        "colors": ["red", "blue"],
        "minY": [0, 0],
        "maxY": [100, 100],
        "scale": "linear"
      }
    },
    {
      "type": "fft-plot",
      "category": "Audio",
      "name": "FFT Plot",
      "dataSource": "audio",
      "configuration": {
        "xAxis": "frequency",
        "yAxis": "amplitude",
        "color": "green"
      }
    },
    {
      "type": "gauge",
      "category": "Pressure",
      "name": "Pressure Gauge",
      "dataSource": "pressure",
      "configuration": {
        "min": 0,
        "max": 100,
        "unit": "Pa"
      }
    },
    {
      "type": "gps-map",
      "category": "Location",
      "name": "GPS Map",
      "dataSources": ["latitude", "longitude"],
      "configuration": {}
    },
    {
      "type": "bar-indicator",
      "category": "Battery",
      "name": "Battery Level Indicator",
      "dataSource": "battery",
      "configuration": {
        "min": 0,
        "max": 100,
        "unit": "%"
      }
    },
    {
      "type": "led-panel",
      "category": "Status",
      "name": "Status Indicator",
      "dataSource": "status",
      "configuration": {
        "color": "green",
        "label": "Active"
      }
    },
    {
      "type": "textual-data",
      "category": "Location",
      "name": "Latitude and Longitude Display",
      "dataSources": ["latitude", "longitude"],
      "configuration": {
        "labels": ["Latitude:", "Longitude:"],
        "units": ["°", "°"]
      }
    },
    {
      "type": "compass",
      "category": "Navigation",
      "name": "Compass",
      "dataSource": "heading",
      "configuration": {}
    },
    {
      "type": "altimeter",
      "category": "Altitude",
      "name": "Altimeter",
      "dataSource": "altitude",
      "configuration": {
        "unit": "m"
      }
    },
    {
      "type": "gyroscope",
      "category": "Motion",
      "name": "Gyroscope",
      "dataSources": ["gyroX", "gyroY", "gyroZ"],
      "configuration": {
        "units": "°/s"
      }
    },
    {
      "type": "accelerometer",
      "category": "Motion",
      "name": "Accelerometer",
      "dataSources": ["accelX", "accelY", "accelZ"],
      "configuration": {
        "units": "m/s²"
      }
    }
  ]
}
```

This proposed format has the following advantages:
- Supports different data formats:
    - CSV like (what Serial Studio currently supports)
    - Hex/binary
    - Key/value pairs
- A single project can parse multiple frame formats
- We separate data reading from the "GUI" part (widgets, plots, etc)
- We can also provide MQTT settings straight from the project file

An example Arduino project for the project format above would be:

```cpp
#include <Arduino.h>

float randomFloat(float min, float max) {
  return min + static_cast<float>(rand()) / (static_cast<float>(RAND_MAX / (max - min)));
}

void sendHexFrame() {
  byte frame[] = {0xAA, 0x41, 0x4D, 0x50, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0xFF};
  float temperature = randomFloat(20, 30);
  float humidity = randomFloat(30, 60);
  int light = random(500, 1000);
  byte status = random(0, 2);
  byte battery = random(30, 100);

  memcpy(frame + 1, &temperature, 4);
  memcpy(frame + 5, &humidity, 4);
  memcpy(frame + 9, &light, 2);
  memcpy(frame + 11, &status, 1);
  memcpy(frame + 12, &battery, 1);

  Serial.write(frame, sizeof(frame));
  Serial.print('\n');
}

void sendCsvFrame() {
  float pressure = randomFloat(900, 1100);
  float altitude = randomFloat(100, 500);
  Serial.print('<');
  Serial.print(pressure);
  Serial.print(',');
  Serial.print(altitude);
  Serial.print('>');
  Serial.print('\n');
}

void sendKeyValueFrame() {
  float latitude = randomFloat(40.6, 40.8);
  float longitude = randomFloat(-74.1, -73.9);
  Serial.print('{');
  Serial.print("lat=");
  Serial.print(latitude);
  Serial.print(";lon=");
  Serial.print(longitude);
  Serial.print('}');
  Serial.print('\n');
}

void setup() {
  Serial.begin(9600);
  randomSeed(analogRead(0));
}

void loop() {
  sendHexFrame();
  delay(1000);

  sendCsvFrame();
  delay(1000);

  sendKeyValueFrame();
  delay(1000);
}
```

Using this new format would also solve issues #134 and #28, also, maybe we could also modify this format to address issues #104, #25 and #87.

Of course, implementing this format would mean that Serial Studio would not support the previous JSON formats, and many things would need to be changed across the code base (which I plan to do, the project grew too fast and a little revamping from the ground is beginning to be necessary). What do you think about this new format? Do you have any suggestions before I start working on this new format?

**Comment by alex-spataru** [comment]
Please take a look at the [frame parser function](https://github.com/Serial-Studio/Serial-Studio/wiki/Project-Editor#frame-parser-function-view). It enables users to write custom JavaScript code for their projects, providing far more flexibility than any JSON-based protocol or structure could offer.

The core idea in this case, is to create a “global” dashboard encompassing all frame types, with the JavaScript parser updating a global array based on the detected frame type. This approach also supports building dashboards from binary data, as demonstrated in the [HexadecimalADC example](https://github.com/Serial-Studio/Serial-Studio/tree/master/examples/HexadecimalADC) and the [BLE iPhone Battery Level demo](https://github.com/Serial-Studio/Serial-Studio/issues/220#issuecomment-2474466995).
