### ISSUE TITLE
Data Format

### ISSUE THREAD

**Issue by schuppeste** [Serial-Studio/Serial-Studio#97]
Hi, nice work!

How i can skip first char of every value, Parse example: 

A123.6 B123.56\r\n

**Comment by elschopi** [comment]
I'd say the easiest solution would be to have your sent data properly formatted. So, for example, send
`/*123.6;123.56*/`
You'll only need to transmit the values to SerialStudio and use the JSON editor to assign the value to a certain location, sensor or other.

**Comment by schuppeste** [comment]
I can Change the Code, No Problem.

have only this Output from a Machines Serial.
